### ISSUE TITLE
Anchoring rules to only be active after an anchored commit

### ISSUE THREAD

**Issue by neilnaveen** [gittuf/gittuf#291] opened 2024-01-25 19:37 UTC
### Add a description

Currently, it would be tough for an established repository to utilize gittuf since past changes in the repository could make created rules become immediately violated. 

For example, if Contributor A has made past commits to the main branch and then left

Now, a rule has been added to protect the main branch, but Contributor A's key is not in the rules. Because of this, the rule will constantly be broken unless it is possible to anchor a rule to a commit and define at the rule's creation that it would only be active for commits after a certain point. 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by adityasaky** [comment] 2024-01-25 20:28
That's how gittuf already works. We use the RSL to identify which policy was applicable at the time a change was made. I'm closing this, please reopen and tag this as a bug if you've run into a situation where this isn't true.

**Closed by adityasaky** 2024-01-25 20:28 UTC
Labels: discussion

**Comment by neilnaveen** [comment] 2024-01-25 22:20
Could you re-open this issue? I ran into this issue when I was experimenting with creating rules on gittuf itself. On my clone of gittuf I created a rule to protect tag v0.0.1 with my own key, and when I ran gittuf verify-tag, it failed since my signing key is different from the signing key used to create the tag.

**Comment by adityasaky** [comment] 2024-01-25 22:23
That's intended behavior if you didn't add my GPG key to the policy. To check:

* Initialize gittuf using your own root of trust keys
* Add a policy that protects `git:refs/tags/v*` with two keys: my GPG key and your test key
* Create an RSL entry for a tag signed by your test key

Now, when you verify-tag, it should work because it verifies that the RSL entry for the tag is signed by a trusted key (yours) and the tag itself is signed by a trusted key (my GPG key).

**Comment by neilnaveen** [comment] 2024-01-25 22:26
But lets say we want to create a rule, from this moment saying that nobody, other than my signing key is allowed to change the tag's ref, but since the previous tag had been made with your signing key, it would fail verification. This is for the specific situation where people from before do not have the same write access they used to when the rule is being created or modified

**Comment by adityasaky** [comment] 2024-01-25 22:32
Sure, but the previous tag would be allowed because of the policy then. New tags would not be allowed as the policy now disallows it. When verifying an old tag, we would use the policy available in the RSL before the tag was added to the RSL. If that policy includes my key, my signature on the tag is valid. If the next policy removes my key, I can't sign tags and record them in the RSL after that policy. Note that the only thing that matters is the order of events in the RSL. So the "when" of an action is mapped to when it enters the RSL, not whether it happened in October or January.

**Comment by neilnaveen** [comment] 2024-01-25 22:37
But what happens if gittuf was not initialize on the repo when the project was created or before the tag was created, only afterwards?

**Comment by adityasaky** [comment] 2024-01-26 15:47
I don't want to generalize too much but the primary target of a security system such as gittuf is to provide guarantees going _forward_. That said, we could discuss how to run through a first-time only "here's the first policy by which these things that technically happened in the past are trusted, with RSL entries for them now". We have support for that for testing purposes in developer mode, but I'm not sold on whether that's truly desirable during standard workflows.
